clone:
  depth: full
pipelines:
  default:
    - step:
        script:
          - git push --mirror git@github.com:https://github.com/agrega-dev/Convertir_Incidente_a_Servicio.git
            variables:
              EXTRA_ARGS: '--exclude=YOUR_DESIRE_FOLDER_PATH/*'
